accounts/urls.py
from django.urls import path
from .views import RegisterView, LoginView, logout_view

app_name = 'accounts'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),

]

event/urls.py
from django.urls import path

from event.views import event, category

app_name = 'event'
urlpatterns = [
    path('', event.view, name='events'),
    path('category/<int:categoryId>', event.view, name='eventsCat'),
    path('createEvents', event.create, name='create'),
    path('editEvents/<int:eventId>', event.edit, name='edit'),
    path('deleteEvents/<int:eventId>', event.delete, name='delete'),

    path('createCategory', category.create, name='createCategory'),
    path('editCategory/<int:categoryId>', category.edit, name='editCategory'),
    path('deleteCategory/<int:categoryId>', category.delete, name='deleteCategory'),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url='/static/images/favicon.ico'), name='favicon'),
    path('', include('event.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

event/models.py
from django.db import models
from django.conf import settings


class Category(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Катергория'
        verbose_name_plural = 'Катергории'


class Events(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    check = models.CharField(max_length=3, default='off')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True)
    date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Заметка'
        verbose_name_plural = 'Заметки'

event/views/category.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from event.models import Category
from event.tools import tools
from django.contrib import messages


@login_required()
def create(request):
    categoryAvailable = tools.is_category_available(request, Category)
    if categoryAvailable:
        Category.objects.create(
            user=request.user,
            title=request.POST['category']
        )
    else:
        messages.error(request, "Категория уже существует!")
    return HttpResponseRedirect(reverse('event:events'))


@login_required()
def edit(request, categoryId):
    category = tools.get_category_or_false(request, Category, categoryId)
    print(category)
    print()
    print()
    if category:
        category.title = request.POST['category']
        category.save()
    else:
        messages.error(request, "Категория уже существует!")


    return HttpResponseRedirect(reverse('event:events'))


@login_required()
def delete(request, categoryId):
    category = Category.objects.get(id=categoryId)
    category.delete()

    return HttpResponseRedirect(reverse('event:events'))

event/views/event.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from datetime import datetime
from django.contrib.auth.decorators import login_required
from event.models import Events, Category
from event.tools import tools


@login_required()
def view(request, categoryId=0):
    context = dict()
    if (categoryId):
        events = Events.objects.filter(category_id=categoryId, user=request.user).order_by('-date')
        try:
            category = Category.objects.get(id=categoryId, user=request.user)
        except Category.DoesNotExist:
            return HttpResponseRedirect(reverse('event:events'))
        context['category'] = category
    else:
        events = Events.objects.filter(user=request.user).order_by('-date')

    categories = Category.objects.filter(user=request.user)

    context['events'] = events
    context['categories'] = categories
    return render(request, 'events/events.html', context)


@login_required()
def create(request):
    check = tools.get_check(request)
    category = tools.get_category(request, Category)
    category.events_set.create(
        user=request.user,
        title=request.POST['title'],
        text=request.POST['text'],
        check=check
    )

    return HttpResponseRedirect(reverse('event:events'))


@login_required()
def edit(request, eventId):
    event = Events.objects.get(id=eventId)
    event.title = request.POST['title']
    event.text = request.POST['text']
    event.category_id = tools.get_category_id(request, Category)
    event.check = tools.get_check(request)
    event.date = datetime.now()
    event.save()

    return HttpResponseRedirect(reverse('event:events'))


@login_required()
def delete(request, eventId):
    event = Events.objects.get(id=eventId)
    event.delete()

    return HttpResponseRedirect(reverse('event:events'))

event/templates/events/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <link rel="stylesheet" href="{% static 'events/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'events/fonts/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'events/fonts/fonts/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'events/css/main.css' %}">
</head>

<body>

{% block modal %}
{% endblock modal %}
{% block body %}
    <div class="container-fluid main d-flex align-content-center justify-content-center">
        <div class="row sub-main">

            <div class="col-12 col-md-8 col-lg-6 p-0">
                <div class="card">
                    <div class="card-body">
                        <div class="container-fluid m-0 p-0">

                            {% block main %}
                            {% endblock main %}
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
{% endblock body %}
{% if messages %}
    <div class="alert-div">
        {% for message in messages %}
            <div class="alert alert-dismissible fade show" role="alert">
                <strong>Ошибка!</strong> {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
{#            <div class="toast bg-danger" role="alert" aria-live="assertive" aria-atomic="true"#}
{#                 data-delay="5000">#}
{#                <div class="toast-header">#}
{#                    <strong class="mr-auto">Ошибка</strong>#}
{#                    <button type="button" class="ml-2 mb-1 close" data-dismiss="toast"#}
{#                            aria-label="Close">#}
{#                        <span aria-hidden="true">&times;</span>#}
{#                    </button>#}
{#                </div>#}
{#                <div class="toast-body">#}
{#                    <p>{{ message }}</p>#}
{#                </div>#}
{#            </div>#}
        {% endfor %}
    </div>
{% endif %}

<script src="{% static 'events/js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'events/js/popper.min.js' %}"></script>
<script src="{% static 'events/js/bootstrap.min.js' %}"></script>
{% block scripts %}

{% endblock scripts %}
</body>


</html>

event/templates/events/events.html
{% extends 'events/main.html' %}
{% block category_select %}
    {% for cat in categories %}
        <option value="{{ cat.id }}" {% if cat.id == 1 %}selected{% endif %}>{{ cat.title }}</option>

    {% endfor %}
{% endblock category_select %}
{% block category %}
    <a class="dropdown-item" href="{% url 'event:events' %}">Все категории</a>
    {% for cat in categories %}
        <a class="no-underline-a" href="{% url 'event:eventsCat' cat.id %}">
        <div class="dropdown-item cat d-flex justify-content-between align-items-center">
            {{ cat.title }}
            <object>
                <a href="#" class="change-event" data-toggle="modal"
               data-target="#modalCategory" data-text="{{ cat.title }}" data-idcat="{{ cat.id }}"><i
                    class="fas fa-cog"></i></a>
            </object>
        </div>
        </a>

    {% endfor %}
{% endblock category %}
{% block events %}
    {% for event in events %}
        <div class="col-12 border-top">
            <div class="d-flex align-items-center">
                {% if event.check == 'on' %}
                    <i class="mr-2 fas fa-square"></i>
                {% endif %}
                <div
                        class=" pass w-100 event-head d-flex justify-content-between align-items-center">
                    <a href="#" class="link" data-toggle="modal" data-target="#modalEvent"
                       data-title="{{ event.title }}" data-text="{{ event.text }}"
                       data-category-id="{{ event.category.id }}" data-category-title="{{ event.category.title }}" data-check="{{ event.check }}"
                       data-idevent="{{ event.id }}" data-no="yes">
                        <h2>{{ event.title }}</h2>
                    </a><a href="{% url 'event:delete' event.id %}" class=""><i
                        class="delete-event fas fa-times"></i></a>
                </div>
            </div>
            <p>{{ event.text }}</p>
            {#            <em class="d-block text-right">Ср 20:10, 2 октября 2019 г.</em>#}
            <em class="d-block text-right">{{ event.date }}</em>
        </div>
    {% endfor %}

{% endblock events %}
{% block categoryTitle %}
    <h4 class="ml-2">{{ category.title }}</h4>
{% endblock %}

event/templates/events/main.html
{% extends 'events/base.html' %}{% load static %}
{% block modal %}
    <!-- Modal event -->
    <div class="modal fade" id="modalEvent" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Создание заметки</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'event:create' %}" method="POST" id="formEvent">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="title" class="col-form-label">Заголовок</label>
                            <input type="text" class="form-control" id="title" name="title">
                        </div>
                        <div class="form-group">
                            <label for="text">Текст</label>
                            <input type="text" class="form-control" id="text" name="text">
                        </div>
                        <div class="form-group">
                            <label for="category">Категория</label>
                            <div class="row">


                                <div class="col">
                                    <input type="text" class="form-control" id="category-title"
                                           name="category" required>
                                </div>
                                <div class="col">
                                    <select class="form-control" id="category">
                                        {% block category_select %}

                                        {% endblock category_select %}
                                    </select>
                                </div>
                            </div>

                        </div>
                        <div class="form-group">
                            <label for="cbx" class="label-cbx">
                                <input id="cbx" type="checkbox" class="invisible" name="check">
                                <div class="checkbox">
                                    <svg width="20px" height="20px" viewBox="0 0 20 20">
                                        <path d="M3,1 L17,1 L17,1 C18.1045695,1 19,1.8954305 19,3 L19,17 L19,17 C19,18.1045695 18.1045695,19 17,19 L3,19 L3,19 C1.8954305,19 1,18.1045695 1,17 L1,3 L1,3 C1,1.8954305 1.8954305,1 3,1 Z"></path>
                                        <polyline points="4 11 8 15 16 6"></polyline>
                                    </svg>
                                </div>
                                <span>Выделить</span>
                            </label>
                        </div>
                        <button type="submit" class="create-event btn create" id="button">Создать</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal category -->
    <div class="modal fade" id="modalCategory" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Создание категории</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'event:createCategory' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="categoryText">Категория</label>
                            <input type="text" class="form-control" id="categoryText" name="category" required>
                        </div>
                        <div class="d-flex justify-content-between">
                            <button type="submit" class="create create-event btn"
                                    id="button">Создать
                            </button>
                            <a href="" id="delete-category" class="delete-category d-flex align-items-center"><i
                                    class="fas fa-trash"></i></a>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
{% endblock modal %}
{% block main %}

    <nav class="row m-0 p-0">
        <div class="col d-flex p-0">
            <div class="d-flex mr-auto">
                <button type="button"
                        class="create-event create-event-link rounded-circle border-0 btn create"
                        data-toggle="modal"
                        data-target="#modalEvent" rel="tooltip" data-no="no" data-placement="top" title="Создать"
                        data-delay='{"show":"400", "hide":"100"}'>
                    <i class="fas fa-plus"></i>
                </button>
                <div class="dropdown ml-2">
                    <a class="create category btn border-0" href="#"
                       role="button"
                       id="dropdownMenuLink" rel="tooltip" data-toggle="dropdown" aria-haspopup="true"
                       aria-expanded="false" data-placement="top" title="Категории"
                       data-delay='{"show":"400", "hide":"100"}'>
                        <i class="fas fa-list-ul"></i>
                    </a>

                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <button type="button"
                                class="dropdown-item btn create-category"
                                data-toggle="modal" data-target="#modalCategory">
                            Категория <i class="fas fa-edit"></i>
                        </button>
                        {% block category %}

                        {% endblock category %}
                    </div>
                </div>
                {% block categoryTitle %}
                {% endblock %}
            </div>
            <div>
                {# Выход#}
                <a href="{% url 'accounts:logout' %}"
                   class="create-event create-event-link rounded-circle border-0 btn create" rel="tooltip"
                   data-placement="top" title="Выход" data-delay='{"show":"400", "hide":"100"}'>
                    <i class="fas fa-sign-out-alt"></i>
                </a>

            </div>
        </div>
    </nav>
    {% if request.user.is_authenticated %}

        <div class="row mt-3 scroll-container" id="style-2">
            {% block events %}
            {% endblock events %}
        </div>
    {% endif %}

{% endblock main %}
{% block scripts %}
    <script>
        $('.toast').toast('show');
    </script>
    <script>
        $('#delete-category').click(function () {
            alert("При удалении категории исчезнут все связанные заметки. Вы уверены?");
        });
    </script>
{#    <script>#}
{#        $(function () {#}
{#            $('[rel="tooltip"]').tooltip();#}
{#        });#}
{#    </script>#}
    <script>
        $('#category').on('change', function () {
            let category = $('#category option:selected').text();
            $('#category-title').val(category);
        });
    </script>
    <script>
        $('form').find('input').attr('autocomplete', 'off');
        $('#modalEvent').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget); // Button that triggered the modal
            var eventTitle = button.data('title');
            var eventText = button.data('text');
            var categoryId = button.data('category-id');
            var categoryTitle = button.data('category-title');
            var check = button.data('check');
            var eventId = button.data('idevent');
            var no = button.data('no');
            var modal = $(this);

            if (no == 'yes') {
                modal.find('.modal-body form').attr('action', "/editEvents/" + eventId);
                modal.find('.modal-title').text('Редактирование ' + eventTitle);
                modal.find('.modal-body #title').val(eventTitle);
                modal.find('.modal-body #text').val(eventText);
                if (check == 'on') {
                    modal.find('.modal-body #cbx').attr('checked', 'true');
                }
                modal.find('#button').text('Сохранить');
                modal.find('#category').show();
            } else {
                modal.find('.modal-body form').attr('action', "/createEvents");
                modal.find('.modal-title').text('Создание');
                modal.find('.modal-body #title').val('');
                modal.find('.modal-body #text').val('');
                modal.find('#button').text('Создать');
                if (!$('#category').val()) {
                    modal.find('#category').hide();
                }
            }
            if (categoryId) {
                modal.find('.modal-body #category').val(categoryId);
                modal.find('.modal-body #category-title').val(categoryTitle);
            } else {
                let category = $('#category option:selected').text();
                modal.find('.modal-body #category-title').val(category);
            }
            modal.find('.modal-body #check').prop('checked', check);
        });
        $('#modalCategory').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget);
            var textCategory = button.data('text');
            var categoryId = button.data('idcat');
            var modal = $(this);
            if (textCategory) {
                modal.find('.modal-title').text('Редактирование ' + textCategory);
                modal.find('#button').text('Сохранить');
                modal.find('.modal-body a').attr('href', '/deleteCategory/' + categoryId);
                modal.find('.modal-body form').attr('action', "/editCategory/" + categoryId);
                modal.find('.fa-trash').show();
            } else {
                modal.find('.modal-body form').attr('action', "/createCategory");
                modal.find('.modal-title').text('Создание');
                modal.find('.modal-body #title').val('');
                modal.find('#button').text('Создать');
                modal.find('.fa-trash').hide();
            }
            modal.find('.modal-body #categoryText').val(textCategory);
        });
    </script>
{% endblock scripts %}